package exception_;

public class Demo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int d=0;
		try {
		int a=55/0;//exception occured
		System.out.println("hello");
		}
		catch(ArithmeticException e) {
			System.out.println("hellosssssssssss");
		}
	}

}
